spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /db
  jpa: 
    hibernate:
      ddl-auto: update
      
server:
  port: 8090
